### PR TITLE
Add activity alias to AndroidManifest.xml

### PR DESCRIPTION
**Pull request by amitkma**
Add an activity alias attribute in AndroidManifest.xml so that there is no need to add/remove intent filters to change the launhcer activity.
It is helpful in case we want to change the launch activity later without breaking homescreen shortcuts. Note must be defined after the targetActivity.

### CODE REVIEW

**Comment by apgapg** [comment]
@arish15 Thankyou for showing interest in Reweyou. We appreciate your efforts towards improving us. We will surely entertain your patch after being verified by our developers. Thankyou

Regards
Reweyou

**Comment by amitkma** [comment]
Well first of all I would like to say that you should atleast follow a architecture. You are building an app which is already in production still don't have any architecture and also not a proper git branching model. Otherwise there is no mean of open source. I like your efforts but efforts should be in right direction for maximum productibility. This is good if only 2 or 3 devs in team but after some time your team will have more than that. In that, you can't go with it. This architecture (if it is) is not scalable and clean at all. 
My final words are nothing is perfect but don't do anything just for the sake of doing it.

**Comment by apgapg** [comment]
@arish15 Thankyou again for your response. We actually like to tell you that we are in a growing stage, and yes there might be some flaws related to our code, and we working at our best to overcome them. We are really delighted that you pointed out our mistakes and the same are already forwarded to our team. Thankyou

Regards
Reweyou

**Comment by varunn12** [comment]
We are committed to use the best practices available as we grow and any input that takes us to that direction is highly appreciated.

We assure you all these suggestions or any new suggestion will be duly considered.

Thank you :)

Cheers,
Varun

**Comment by orcadot** [comment]
Thanks Varun for considering my suggestions. Using best practices makes your app more optimized and clean, Don't categorize the code based on layer but categorize it on the basis of features. 

Regrads,
Amit

**Pull request closed without merging**
